version: 2.1

executors:
  nebula-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
  cypress:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo

jobs:
  dependencies:
    executor: nebula-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - yarn-packages-$CACHE_VERSION-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-${CACHE_VERSION}-{{ .Branch }}-
            - yarn-packages-v1-

      - run:
          name: Install dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn cache
          key: yarn-packages-${CACHE_VERSION}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress

      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - .ssh/known_hosts
            - .npmrc
            - .cache/Cypress

  test:
    executor: nebula-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test
          command: yarn test --maxWorkers 2 --ci --reporters=default --reporters=jest-junit

  visual-build:
    executor: nebula-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build the app
          command: yarn build
          environment:
            NODE_ENV: development
            LOCAL_DOMAIN: localhost
            LOCAL_PORT: "9000"

      - persist_to_workspace:
          root: .
          paths:
            - build

  visual:
    executor: cypress
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Verify that Cypress can run
          command: npx cypress verify
      - run:
          name: Cypress & Percy
          command: yarn percy exec -- yarn visual run --record false --key ${CYPRESS_TOKEN} --config video=true

  build:
    executor: nebula-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build

  semantic-release:
    executor: nebula-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy
          command: yarn semantic-release

workflows:
  version: 2
  workflow:
    jobs:
      - dependencies:
          context: global
      - test:
          requires:
            - dependencies
      - visual-build:
          requires:
            - dependencies
      - visual:
          context: global
          requires:
            - dependencies
            - visual-build
      - build:
          requires:
            - dependencies
      - semantic-release:
          context: global
          requires:
            - dependencies
            - test
            - build
