version: 2.1

executors:
  nebula-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

jobs:
  dependencies:
    executor: nebula-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  test:
    executor: nebula-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test
          command: yarn test --maxWorkers 2 --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: 'test-results/Jest/js-test-results.xml'
      - store_test_results:
          path: test-results

  build:
    executor: nebula-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build

  semantic-release:
    executor: nebula-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy
          command: yarn semantic-release

workflows:
  version: 2
  workflow:
    jobs:
      - dependencies:
          context: global
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - dependencies
      - semantic-release:
          context: global
          requires:
            - dependencies
            - test
            - build
